#!/usr/bin/env bun

const packageJson = await Bun.file(new URL("../package.json", import.meta.url)).json();
const version = String(packageJson.version ?? "").trim();
const outputUrl = new URL("../src/generated/version.ts", import.meta.url);
const expectedOutput = `// This file is generated by scripts/sync-version.mjs.\nexport const CLI_VERSION = ${JSON.stringify(version)};\n`;
const checkOnly = process.argv.includes("--check");

if (!version) {
  console.error('sync-version: package.json is missing a valid "version".');
  process.exit(1);
}

const currentOutput = await Bun.file(outputUrl).text().catch(() => "");
if (currentOutput === expectedOutput) {
  process.exit(0);
}

if (checkOnly) {
  console.error(
    `sync-version: src/generated/version.ts is stale. Run "bun run version:sync" after changing package.json version.`,
  );
  process.exit(1);
}

await Bun.write(outputUrl, expectedOutput);
